# Theme aligned with niri/dms/colors.kdl

[main]
font=Lilex Nerd Font:size=11
terminal=ghostty
layer=overlay
width=45
lines=12
horizontal-pad=16
vertical-pad=12
inner-pad=8
prompt="❯ "

[border]
width=2
radius=5

[colors]
background=292522f2
text=ece1d7ff
prompt=817567ff
placeholder=817567ff
input=ece1d7ff
match=805610ff
selection=633f00ff
selection-text=ece1d7ff
selection-match=ebc06dff
counter=817567ff
border=805610ff
