[helpers]

[default]
depends = ["scripts"]

[scripts.files]
scripts = "~/.local/bin/"
[cargo.files]
cargo = "~/.cargo"

[zed.files]
"zed-settings.jsonc" = "~/.config/zed/settings.json"
"zed-keymap.jsonc" = "~/.config/zed/keymap.json"
"zed/themes" = "~/.config/zed/themes"

[agents.files]
"agents" = "~/.agents"
"pi" = "~/.pi"

[bat.files]
bat = "~/.config/bat"

[alacritty.files]
"alacritty" = "~/.config/alacritty/"
[alacritty]
depends = ["nu", "fonts"]

[foot.files]
"Wayland/foot" = "~/.config/foot/"
[foot]
depends = ["nu", "fonts"]

[fonts.files.fonts]
"target" = "~/.local/share/fonts/"
"type" = "symbolic"

[nu.files]
nushell = "~/.config/nushell"

[nu]
depends = ["starship", "helix", "nvim"]

[starship.files]
"starship.toml" = "~/.config/starship.toml"
"starship-jj.toml" = "~/.config/starship-jj/starship-jj.toml"

[helix.files]
helix = "~/.config/helix"

[nix.files]
nix = "~/.config/nix"

[kwm]
depends = ["kwim", "tofi"]
[kwm.files."Wayland/kwm/config.zon"]
target = "~/.config/kwm/config.zon"
type = "symbolic"

[kwm.files."Wayland/kwm/kwm-status"]
target = "~/.config/kwm/kwm-status"
type = "symbolic"

[kwm.files."Wayland/kwm/theme-menu"]
target = "~/.config/kwm/theme-menu"
type = "symbolic"

[kwm.files."Wayland/kwm/audio-output-menu"]
target = "~/.config/kwm/audio-output-menu"
type = "symbolic"

[kwm.files."Wayland/kwm/bluetooth-menu"]
target = "~/.config/kwm/bluetooth-menu"
type = "symbolic"

[kwm.files."Wayland/kwm/power-profile-menu"]
target = "~/.config/kwm/power-profile-menu"
type = "symbolic"

[kwm.files."Wayland/kwm/tofi-menu"]
target = "~/.config/kwm/tofi-menu"
type = "symbolic"

[kwim.files."Wayland/kwim/config.zon"]
target = "~/.config/kwim/config.zon"
type = "symbolic"

[nvim.files]
nvim = "~/.config/nvim"

[emacs.files]
"emacs" = "~/.config/emacs"

[exwm.files]
"exwm/exwm.Desktop" = "~/.local/share/xsessions/exwm.Desktop"
"exwm/udiskie/config.yml" = "~/.config/udiskie/config.yml"
[exwm]
depends = ["emacs"]

[ghostty.files]
ghostty = "~/.config/ghostty"

[tmux.files]
tmux = "~/.config/tmux"

[niri.files]
"Wayland/niri" = "~/.config/niri"
[niri]
depends = ["fuzzel"]

[river.files]
"Wayland/river" = "~/.config/river"
[river]
depends = ["kwm", "mako", "kanshi", "foot"]

[kanshi.files]
"Wayland/kanshi" = "~/.config/kanshi"

[mako.files]
"Wayland/mako" = "~/.config/mako"

[fuzzel.files]
"Wayland/fuzzel" = "~/.config/fuzzel"

[tofi.files]
"Wayland/tofi" = "~/.config/tofi"

[vdirsyncer.files]
"vdirsyncer/config" = "~/.vdirsyncer/config"

[settings]
default_target_type = "automatic"

[default.variables]
