[helpers]

[default]
depends = ["alacritty", "zed"]

[cargo.files]
cargo = "~/.cargo"

[zed.files]
"zed-settings.jsonc" = "~/.config/zed/settings.json"
"zed-keymap.jsonc" = "~/.config/zed/keymap.json"

[agents.files]
"agents" = "~/.agents"
"pi" = "~/.pi"

[alacritty.files]
"alacritty" = "~/.config/alacritty/"
[alacritty]
depends = ["nu", "fonts"]

[foot.files]
"foot" = "~/.config/foot/"
[foot]
depends = ["nu", "fonts"]

[fonts.files.fonts]
"target" = "~/.local/share/fonts/"
"type" = "symbolic"

[nu.files]
nushell = "~/.config/nushell"

[nu]
depends = ["starship", "helix"]

[starship.files]
"starship.toml" = "~/.config/starship.toml"
"starship-jj.toml" = "~/.config/starship-jj/starship-jj.toml"

[helix.files]
helix = "~/.config/helix"

[nvim.files]
nvim = "~/.config/nvim"

[ghostty.files]
ghostty = "~/.config/ghostty"

[tmux.files]
tmux = "~/.config/tmux"

[niri.files]
niri = "~/.config/niri"

[settings]
default_target_type = "automatic"

[default.variables]
