(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(pixel-scroll-precision-mode 1)
(global-auto-revert-mode 1)
(setq scroll-conservatively 101
      scroll-margin 5
      use-dialog-box nil)
(setq
 inhbit-startup-message t
 visible-bell t
 )

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  ;(meow-motion-define-key
  ; '("j" . meow-next)
  ; '("k" . meow-prev)
  ; '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet)
   '("." . find-file)
   '("SPC" . project-find-file)
   '("w v" . split-window-right)
   '("w s" . split-window-below)
   '("w d" . delete-window)
   '("b b" . switch-to-buffer)
   '("b n" . buffer-next))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(require 'meow)
(meow-setup)
(meow-global-mode 1)

(setq custom-file (locate-user-emacs-file "custom-vars.el"))
(load custom-file 'noerror 'nomessage)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(setq
 modus-themes-mixed-fonts t
 modus-themes-variable-pitch-ui t
 modus-themes-common-palette-overrides '((border-mode-line-active bg-mode-line-active)
					 (border-mode-line-inactive bg-mode-line-inactive)
					 (fringe unspecified)
					 (string green-cooler)
					 (comment yellow-cooler)
					 )
 )

(add-to-list 'default-frame-alist
             '(font . "Lilex Nerd Font-10"))
(load-theme 'tao-yin t)
;; test
(recentf-mode 1)
(setq history-length 25)
(savehist-mode 1)
(save-place-mode 1)

(require 'package)
(package-initialize)

(setq display-time-default-load-average nil)
(display-time-mode 1)
(display-battery-mode 1)
(icomplete-vertical-mode 1)
(server-start)

(require 'exwm)
;; Make Caps Lock act as Control for EXWM.
(call-process "setxkbmap" nil nil nil "-option" "ctrl:nocaps")
(setq exwm-workspace-number 4)
(setq exwm-input-global-keys
      `(
	([?\s-r] . exwm-reset)
	([?\s-w] . exwm-workspace-switch)
	([?\s-p] . (lambda (cmd)
		     (interactive (list (read-shell-command "$ ")))
		     (start-process-shell-command cmd nil cmd)))))
(defun exwm-async-run (name)
  "Run a process asynchronously"
  (interactive)
  (start-process name nil name))

(defun run-or-raise-or-dismiss (program program-buffer-name)
  ""
  (if (string= (buffer-name) program-buffer-name)
      (bury-buffer)
    (progn
      (if (get-buffer program-buffer-name)
	  (progn
	    (if (get-buffer-window program-buffer-name)
		(select-window (display-buffer program-buffer-name) nil)
	      (exwm-workspace-switch-to-buffer program-buffer-name)))
	(exwm-async-run program)))))
(start-process "nm-applet" nil "nm-applet")

(exwm-wm-mode 1)
