;;; system-menus.el --- Desktop menus -*- lexical-binding: t; -*-

(defun my/system-menu--output (program &rest args)
  (with-temp-buffer
    (apply #'call-process program nil t nil args)
    (buffer-string)))

(defun my/audio-output-menu ()
  "Select the default PulseAudio/PipeWire output." 
  (interactive)
  (let* ((default (string-trim (my/system-menu--output "pactl" "get-default-sink")))
         (text (my/system-menu--output "pactl" "list" "sinks"))
         sinks name desc)
    (dolist (line (split-string text "\n"))
      (cond
       ((string-match "^Sink #[0-9]+" line)
        (when name (push (list name desc) sinks))
        (setq name nil desc nil))
       ((string-match "^[[:space:]]*Name: \\(.+\\)$" line)
        (setq name (match-string 1 line)))
       ((string-match "^[[:space:]]*Description: \\(.+\\)$" line)
        (setq desc (match-string 1 line)))))
    (when name (push (list name desc) sinks))
    (setq sinks (nreverse sinks))
    (unless sinks (user-error "No audio outputs found"))
    (let* ((choices (mapcar (lambda (sink)
                              (cons (format "%s %s" (if (string= (car sink) default) "󰓃" "󰓄") (cadr sink)) sink)) sinks))
           (choice (completing-read "Audio output: " choices nil t))
           (sink (cdr (assoc choice choices))))
      (call-process "pactl" nil nil nil "set-default-sink" (car sink))
      (dolist (line (split-string (my/system-menu--output "pactl" "list" "short" "sink-inputs") "\n" t))
        (let ((input (car (split-string line))))
          (call-process "pactl" nil nil nil "move-sink-input" input (car sink))))
      (call-process "notify-send" nil nil nil "Audio output switched" (cadr sink)))))

(defun my/power-profile-menu ()
  "Select the system power profile."
  (interactive)
  (let* ((current (string-trim (my/system-menu--output "powerprofilesctl" "get")))
         (text (my/system-menu--output "powerprofilesctl" "list"))
         profiles)
    (dolist (line (split-string text "\n" t))
      (when (string-match "^[[:space:]]*\\*?[[:space:]]*\\([a-z-]+\\):" line)
        (push (match-string 1 line) profiles)))
    (setq profiles (delete-dups (nreverse profiles)))
    (unless profiles (user-error "No power profiles found"))
    (let* ((choice (completing-read "Power profile: " profiles nil t))
           (profile choice))
      (call-process "powerprofilesctl" nil nil nil "set" profile)
      (call-process "notify-send" nil nil nil "Power profile switched" profile))))

(defun my/theme-menu (&optional choice)
  "Switch the desktop theme, or toggle it when CHOICE is nil." 
  (interactive)
  (let* ((state-file (expand-file-name "color-scheme" (or (getenv "XDG_STATE_HOME") "~/.local/state")))
         (current (if (file-readable-p state-file) (string-trim (with-temp-buffer (insert-file-contents state-file) (buffer-string))) "dark"))
         (choice (or choice (completing-read "Theme: " '("󰜉 Toggle" "󰖨 Light" "󰖔 Dark") nil t)))
         (mode (cond ((string-match-p "Toggle" choice) (if (string= current "dark") "light" "dark"))
                     ((string-match-p "Light" choice) "light")
                     (t "dark")))
         (scheme (if (string= mode "dark") "prefer-dark" "default")))
    (make-directory (file-name-directory state-file) t)
    (call-process "gsettings" nil nil nil "set" "org.gnome.desktop.interface" "color-scheme" scheme)
    (call-process "gsettings" nil nil nil "set" "org.gnome.desktop.interface" "gtk-application-prefer-dark-theme" (if (string= mode "dark") "true" "false"))
    (with-temp-file state-file (insert mode "\n"))
    (call-process "notify-send" nil nil nil "Theme switched" mode)))

(defun my/system-menu ()
  "Open the desktop system menu."
  (interactive)
  (pcase (completing-read "Menu: " '("󰖨 Theme" "󰓃 Audio output" "󰂯 Bluetooth" "󰌪 Power profile") nil t)
    ((pred (string-match-p "Theme")) (my/theme-menu))
    ((pred (string-match-p "Audio")) (my/audio-output-menu))
    ((pred (string-match-p "Bluetooth")) (my/bluetooth-menu))
    ((pred (string-match-p "Power")) (my/power-profile-menu))))

(provide 'system-menus)
