# Zenbones theme

[main]
font=Lilex Nerd Font:size=11
font-bold=Lilex Nerd Font:style=Bold:size=11
font-italic=Lilex Nerd Font:style=Italic:size=11
font-bold-italic=Lilex Nerd Font:style=Bold Italic:size=11
shell=nu
# pad=8x8 center

[mouse]
hide-when-typing=yes

[colors-dark]
foreground = B4BDC3
background = 1C1917
selection-background = 403833
selection-foreground = C4CACF
regular0   = 1C1917
regular1   = DE6E7C
regular2   = 819B69
regular3   = B77E64
regular4   = 6099C0
regular5   = B279A7
regular6   = 66A5AD
regular7   = B4BDC3
bright0    = 403833
bright1    = E8838F
bright2    = 8BAE68
bright3    = D68C67
bright4    = 61ABDA
bright5    = CF86C1
bright6    = 65B8C1
bright7    = C4CACF

[colors-light]
foreground = 2C363C
background = F0EDEC
selection-background = CFC1BA
selection-foreground = 2C363C
regular0   = F0EDEC
regular1   = A8334C
regular2   = 4F6C31
regular3   = 944927
regular4   = 286486
regular5   = 88507D
regular6   = 3B8992
regular7   = 2C363C
bright0    = CFC1BA
bright1    = 94253E
bright2    = 3F5A22
bright3    = 803D1C
bright4    = 1D5573
bright5    = 7B3B70
bright6    = 2B747C
bright7    = 4F5E68
[key-bindings]
spawn-terminal=Control+Shift+n
