;;; zenbones-light-theme.el --- Zenbones light theme -*- lexical-binding: t; -*-

(deftheme zenbones-light "A quiet Zenbones light theme.")

(require 'zenbones-themes)

(let ((comment (if zenbones-more-visible-comments "#943033" "#6E6763"))
      (bg (if zenbones-neutral-background "#FFFCF0" "#F0EDEC"))
      (shadow-bg (if zenbones-neutral-background "#F0EDEC" "#FFFCF0"))
      (bg-alt (if zenbones-neutral-background "#F2F0E5" "#EAE6E4")) (fg "#2C363C")
      (muted "#948985") (blue "#556570") (brown "#6A5549")
      (green "#4F6C31") (red "#A8334C") (punct "#8E817B")
      (border "#E6E0DD"))
  (custom-theme-set-faces
   'zenbones-light
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(region ((t (:background ,border))))
   `(highlight ((t (:background ,bg-alt))))
   `(hl-line ((t (:background ,bg-alt))))
   `(shadow ((t (:foreground ,muted :background ,shadow-bg))))
   `(link ((t (:foreground ,blue :underline t))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,brown :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
   `(font-lock-string-face ((t (:foreground ,(if zenbones-green-strings green blue) :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,fg :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,blue))))
   `(font-lock-function-name-face ((t (:foreground ,fg))))
   `(font-lock-type-face ((t (:foreground ,brown))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(line-number ((t (:foreground ,muted :background ,bg))))
   `(line-number-current-line ((t (:foreground ,fg :background ,bg-alt :weight bold))))
   `(mode-line ((t (:foreground ,fg :background ,bg-alt :box nil))))
   `(mode-line-inactive ((t (:foreground ,muted :background ,bg))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
   `(vertical-border ((t (:foreground ,border))))
   `(header-line ((t (:foreground ,fg :background ,bg-alt :weight bold))))
   `(org-level-1 ((t (:foreground ,brown :weight medium))))
   `(org-level-2 ((t (:foreground ,brown :weight medium))))
   `(org-level-3 ((t (:foreground ,brown :weight medium))))
   `(org-level-4 ((t (:foreground ,brown :weight medium))))
   `(org-level-5 ((t (:foreground ,brown :weight medium))))
   `(org-level-6 ((t (:foreground ,brown :weight medium))))
   `(org-level-7 ((t (:foreground ,brown :weight medium))))
   `(org-level-8 ((t (:foreground ,brown :weight medium))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))))

(provide-theme 'zenbones-light)
;;; zenbones-light-theme.el ends here
