;;; zenbones-dark-theme.el --- Zenbones dark theme -*- lexical-binding: t; -*-

(deftheme zenbones-dark "A quiet Zenbones dark theme.")

(require 'zenbones-themes)

(let ((comment (if zenbones-more-visible-comments "#947063" "#6E6763"))
      (bg (if zenbones-neutral-background "#100F0F" "#1C1917"))
      (shadow-bg (if zenbones-neutral-background "#1C1917" "#100F0F"))
      (bg-alt (if zenbones-neutral-background "#1F1E1D" "#24201D")) (fg "#B4BDC3")
      (muted "#6E6763") (blue "#868C91") (brown "#A1938C")
      (green "#95906A") (red "#DE6E7C") (punct "#867A74")
      (border "#403833"))
  (custom-theme-set-faces
   'zenbones-dark
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(region ((t (:background ,border))))
   `(highlight ((t (:background ,bg-alt))))
   `(hl-line ((t (:background ,bg-alt))))
   `(shadow ((t (:foreground ,muted :background ,shadow-bg))))
   `(link ((t (:foreground ,blue :underline t))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,brown :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
   `(font-lock-string-face ((t (:foreground ,(if zenbones-green-strings green blue) :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,fg :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,blue))))
   `(font-lock-function-name-face ((t (:foreground ,fg))))
   `(font-lock-type-face ((t (:foreground ,brown))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(line-number ((t (:foreground ,muted :background ,bg))))
   `(line-number-current-line ((t (:foreground ,fg :background ,bg-alt :weight bold))))
   `(mode-line ((t (:foreground ,fg :background ,bg-alt :box nil))))
   `(mode-line-inactive ((t (:foreground ,muted :background ,bg))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
   `(vertical-border ((t (:foreground ,border))))
   `(header-line ((t (:foreground ,fg background ,bg-alt :weight bold))))
   `(org-level-1 ((t (:foreground ,fg :weight medium))))
   `(org-level-2 ((t (:foreground ,fg :weight medium))))
   `(org-level-3 ((t (:foreground ,fg :weight medium))))
   `(org-level-4 ((t (:foreground ,fg :weight medium))))
   `(org-level-5 ((t (:foreground ,fg :weight medium))))
   `(org-level-6 ((t (:foreground ,fg :weight medium))))
   `(org-level-7 ((t (:foreground ,fg :weight medium))))
   `(org-level-8 ((t (:foreground ,fg :weight medium))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))))

(provide-theme 'zenbones-dark)
;;; zenbones-dark-theme.el ends here
